apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app
  labels:
    app: weather-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
      - name: weather-app
        image: srbobl071746acr.azurecr.io/myapp:latest   # <-- updated by pipeline
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: weather-secrets   # <-- matches the kubectl secret name
