apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Production Let's Encrypt endpoint
    server: https://acme-v02.api.letsencrypt.org/directory
    # 👇 replace with your email (used for expiry notices, etc.)
    email: your-email@annkursharma.co.in
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
