name: 02-Continuous-Integration - Build & Push Docker Image

on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
    inputs:
      run_sonar:
        description: "Run SonarQube Scan?"
        required: true
        default: "No"
        type: choice
        options:
          - "Yes"
          - "No"

      prepare_artifact:
        description: "Prepare artifact directory and upload?"
        required: true
        default: "No"
        type: choice
        options:
          - "Yes"
          - "No"

      acr_login_upload:
        description: "Upload build image to ACR"
        required: true
        default: "No"
        type: choice
        options:
          - "Yes"
          - "No"

env:
  BUILD_VERSION: "1.4.${{ github.run_number }}"
  ARGOCD_SERVER: "127.0.0.1:8081"
  ACR_PATH: "nierom031143acr.azurecr.io"

permissions:
  contents: write

jobs:
  Continuous-Integration:
    runs-on: self-hosted

    steps:
      # Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Build with Maven
      - name: Build with Maven
        run: mvn -B clean verify install

      # Run SonarQube analysis
      # User input required for execution: input: run_sonar
      - name: SonarQube Scan
        if: ${{ github.event.inputs.run_sonar == 'Yes' }}
        run: |
          sonar-scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        
      # Upload artifact to Nexus
      - name: Deploy to Nexus
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PASS: ${{ secrets.NEXUS_PASS }}
        run: |
          Write-Host "Deploying version $BUILD_VERSION"
      
          # Use double quotes for proper expansion
          mvn deploy:deploy-file `
            "-DgroupId=com.example" `
            "-DartifactId=weather-app" `
            "-Dversion=$env:BUILD_VERSION" `
            "-Dpackaging=war" `
            "-Dfile=target/weather-app.war" `
            "-DrepositoryId=maven-release-repo-weather-app" `
            "-Durl=http://localhost:8899/repository/maven-release-repo-weather-app/" `
            "-Dusername=$env:NEXUS_USER" `
            "-Dpassword=$env:NEXUS_PASS"
        shell: powershell
      
      # User input required for execution: input: prepare_artifact
      - name: Prepare artifact directory
        id: prepare-artifactory
        if: ${{ github.event.inputs.prepare_artifact == 'Yes' }}
        run: |
          mkdir -p application-artifact
          cp target/*.war application-artifact/

      # Executed if "Prepare artifact directory" is "Yes" and "Prepare artifact directory" is successfully executed
      - name: Upload artifact
        if: ${{ github.event.inputs.prepare_artifact == 'Yes' && steps.prepare-artifactory.conclusion == 'success' }}
        uses: actions/upload-artifact@v4.6.2
        with:
          name: weather-app1-${{ env.BUILD_VERSION }}.war
          path: application-artifact

      # Download artifact from Nexus
      - name: Download artifact from Nexus
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PASS: ${{ secrets.NEXUS_PASS }}
        run: |
          $ARTIFACT_URL="http://localhost:8899/repository/maven-release-repo-weather-app/com/example/weather-app/${{ env.BUILD_VERSION }}/weather-app-${{ env.BUILD_VERSION }}.war"
          Invoke-WebRequest -Uri $ARTIFACT_URL -OutFile weather-app-${{ env.BUILD_VERSION }}.war -Credential (New-Object System.Management.Automation.PSCredential($env:NEXUS_USER,(ConvertTo-SecureString $env:NEXUS_PASS -AsPlainText -Force)))

      # Azure login
      # User input required for execution: input: acr_login_upload
      - name: Azure Login
        if: ${{ github.event.inputs.acr_login_upload == 'Yes' }}
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      # Login to ACR
      # User input required for execution: input: acr_login_upload
      - name: Azure Container Registry Login
        if: ${{ github.event.inputs.acr_login_upload == 'Yes' }}
        uses: azure/docker-login@v2
        with:
          login-server: $env:ACR_PATH
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      
      # Docker login to ACR
      # User input required for execution: input: acr_login_upload
      - name: Docker login to ACR
        if: ${{ github.event.inputs.acr_login_upload == 'Yes' }}
        run: |
          az acr login --name $env:ACR_PATH
        shell: powershell

      # Build docker image
      # User input required for execution: input: acr_login_upload
      - name: Build Docker Image
        if: ${{ github.event.inputs.acr_login_upload == 'Yes' }}
        run: |
          docker build `
            --build-arg BUILD_VERSION=${{ env.BUILD_VERSION }} `
            -t $env:ACR_PATH/myapp:${{ env.BUILD_VERSION }} .

      # Push docker image to ACR
      # User input required for execution: input: acr_login_upload
      - name: Push Docker Image
        id: push-docker-image-to-acr
        if: ${{ github.event.inputs.acr_login_upload == 'Yes' }}
        run: |
          docker push $env:ACR_PATH/myapp:${{ env.BUILD_VERSION }}

      # Notify Deployment Repo (optional)
      # User input required for execution: input: acr_login_upload
      # Executed if "acr_login_upload" is "Yes" and "Push Docker Image" is successfully executed
      - name: Notify Deployment Repo
        if: ${{ github.event.inputs.acr_login_upload == 'Yes' && steps.push-docker-image-to-acr.conclusion == 'success' }}
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT_DEPLOY_REPO_CLASSIC_TOKEN }}   # personal access token of Repo 2
          repository: annkur-sharma-devops/AppCode01-WeatherApp-K8s
          event-type: new-image-built
          client-payload: '{"build_version": "${{ env.BUILD_VERSION }}"}'


      # - name: Create/Update Kubernetes Secret
      #   run: |
      #     kubectl create secret generic weather-secrets `
      #       --from-literal=OPENWEATHER_API_KEY=${{ secrets.OPENWEATHER_API_KEY }} `
      #       --dry-run=client -o yaml | kubectl apply -f -
      
      # - name: Update Kubernetes manifest (PowerShell)
      #   shell: powershell
      #   run: |
      #     $file = "k8s/deployment.yaml"
      #     $content = Get-Content $file
      #     $newContent = $content -replace 'image: .*', "image: ${{ env.ACR_PATH }}/myapp:${{ env.BUILD_VERSION }}   # <-- updated by pipeline"
      #     Set-Content $file $newContent

      # - name: Commit manifest update
      #   shell: powershell
      #   run: |
      #     git config --global user.name "github-actions[bot]"
      #     git config --global user.email "github-actions[bot]@users.noreply.github.com"
      #     git add k8s/deployment.yaml
      #     git commit -m "Update deployment.yaml with image tag ${{ env.BUILD_VERSION }}"
      #     git push

